name: 'Life!'
favicon: null
layout_spectrum: 0.55689
typography_spectrum: 0.52131
title: 'Life!.com'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#354044'
    - '#fdfeff'
    - '#536768'
    - '#ced6d8'
    - '#d0d76e'
  brandStrength: 0.5686230678111315
  lightness: 0.23843513568863273
  saturation: 0.11853735707700253
  rhythmicContrast: 0.16643207520246506
purpose: []
